### DISCUSSION TITLE
Transition component should handle leave transition for Transition.Child when it's unmounted

### DISCUSSION THREAD

**Discussion by thiemeljiri** [tailwindlabs/headlessui#2617] [Ideas]
Hi.

From what I've read and tried, achieving the following with `@headlessui/react` `<Transition>` component is impossible. There are cases when it's impossible to simply toggle the content via `show` prop. Very often you need to animate dynamically rendered content. Currently it's impossible with the `<Transition>` component as it doesn't handle the leave animation of unmounted children. It should keep it in the DOM until tre transitions are finished. Without this feature migration is impossible on many projects.

Are there any plans to implement this? Or does any workaround already exist?

Thanks!

-----

In this example the `content` is dynamically changed upon user interaction and it slides to left/right and new content is revealed.
(The altering of the animation direction is also something that is quite often necessary. Both `<CSSTransition>` and `<Transition>` can't handle dynamically changed classes - it won't affect the current transition, but only the next one. This can be solved some other way - class or data attribute on the wrapper and using it in the selectors for the animation classes. But it would be nice if this was also achievable without this workaround.)

```tsx
import { CSSTransition, TransitionGroup } from 'react-transition-group';

...

  <TransitionGroup
    // just an example of CSS classes to be applied, this is not relevant
    className={twMerge(
      'grid grid-cols-[1fr] grid-rows-[auto] overflow-hidden',
      animationDirection === 'left'
        ? 'animate-content-slide-direction--left'
        : 'animate-content-slide-direction--right'
    )}
  >
    <CSSTransition
      key={content.id}
      timeout={300}
      classNames="animate-content-slide-" // 
    >
      {content != null && <>
         {content.answer === 42 ? (
            <SubComponentThatRendersTheConentent
              content={content}
              key={content.id}
            />
          ) : (
            <AnotherSubComponentThatRendersTheConentent
              content={content}
              key={content.id}
            />
          )}
      </>}
    </CSSTransition>
  </TransitionGroup>
```

Example of `<SubComponentThatRendersTheConentent>`:
```tsx
<div className="className="col-span-full row-span-full bg-white">
  <h2>{content.title}</h2>
  {content.body}
</div>
```

Relevant CSS for the example above:
```css
.animate-content-slide-direction--left .animate-content-slide--enter {
  @apply animate-fade-in;
  /* Note: @apply motion-safe:animate-slide-in-left produces wrong output here - possible Tailwind bug; the following works OK */
  @media (prefers-reduced-motion: no-preference) {
    animation: theme('animation.slide-in-left');
  }
}

.animate-content-slide-direction--left .animate-content-slide--exit {
  @apply animate-fade-out;
  @media (prefers-reduced-motion: no-preference) {
    animation: theme('animation.slide-out-left');
  }
}

.animate-content-slide-direction--right .animate-content-slide--enter {
  @apply animate-fade-in;
  @media (prefers-reduced-motion: no-preference) {
    animation: theme('animation.slide-in-right');
  }
}

.animate-content-slide-direction--right .animate-content-slide--exit {
  @apply animate-fade-out;
  @media (prefers-reduced-motion: no-preference) {
    animation: theme('animation.slide-out-right');
  }
}
```
